import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Promo from "@/components/Promo";
import { useState } from "react";
import useSound from "use-sound";
import { Transition } from "@headlessui/react";

export default function Home() {
  const [playAudio] = useSound("party-drop-web.mp3");
  const [ramboHeadIsActivated, setRamboHeadIsActivated] = useState(true);
  const [isPartyExplosionActivated, setIsPartyExplosionActivated] =
    useState(false);
  const [gifSource, setGifSource] = useState("");

  const ramboHeadClickHandler = () => {
    setGifSource("explosion.gif");
    setRamboHeadIsActivated((ramboHeadIsActivated) => !ramboHeadIsActivated);
    setIsPartyExplosionActivated(true);
    playAudio();
    setTimeout(() => {
      setGifSource("");
      setIsPartyExplosionActivated(false);
    }, 2000);
  };

  const ramboHeadClickHandlerNoAudio = () => {
    setRamboHeadIsActivated((ramboHeadIsActivated) => !ramboHeadIsActivated);
  };

  return (
    <>
      <Head>
        <title>Rambo Party Productions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {ramboHeadIsActivated ? (
        <div
          className={`bg-black w-screen h-screen absolute z-50 flex justify-center text-center`}
        >
          <div className="my-auto cursor-pointer">
            <h1 className="text-white text-3xl animate-pulse mb-5">
              click to enter
            </h1>
            <img
              src="rambo-head.png"
              className="cursor-pointer mx-auto"
              onClick={ramboHeadClickHandler}
            />
          </div>
        </div>
      ) : (
        <div>
          <img
            src={gifSource}
            className="absolute mx-auto left-0 right-0 top-0 bottom-0 my-auto w-full  z-20 "
          />

          <Transition
            show={isPartyExplosionActivated}
            leave="transition-opacity duration-500"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <img
              src="rambo-keytar.png"
              className="absolute mx-auto left-0 right-0 top-0 bottom-0 my-auto w-2/3 z-30 "
            />
          </Transition>
        </div>
      )}

      <main>
        <Header ramboHeadActivate={ramboHeadClickHandlerNoAudio} />
        <Promo />
        {ramboHeadIsActivated ? <></> : <Footer />}
      </main>
    </>
  );
}
