import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Promo from "@/components/Promo";
import { useState, useEffect } from "react";
import { client, urlFor } from "client";
import useSound from "use-sound";
import { Transition } from "@headlessui/react";
import { UpcomingEventProps } from "typings";
import Image from "next/image";

export default function Home({ upcomingEvents }: UpcomingEventProps) {
  const [playAudio] = useSound("party-drop-web.mp3");
  const [ramboHeadIsActivated, setRamboHeadIsActivated] = useState(false);
  const [isPartyExplosionActivated, setIsPartyExplosionActivated] =
    useState(false);
  const [gifSource, setGifSource] = useState("");

  useEffect(() => {
    let popUp_status = localStorage.getItem("popUp_status");
    if (!popUp_status) {
      setRamboHeadIsActivated(true);
      localStorage.setItem("popUp_status", "1");
    }
  }, []);

  const ramboHeadClickHandler = () => {
    setGifSource("explosion.gif");
    setRamboHeadIsActivated((ramboHeadIsActivated) => !ramboHeadIsActivated);
    setIsPartyExplosionActivated(true);
    playAudio();
    setTimeout(() => {
      setIsPartyExplosionActivated(false);
      setGifSource("");
    }, 2000);
  };

  const ramboHeadClickHandlerNoAudio = () => {
    setRamboHeadIsActivated((ramboHeadIsActivated) => !ramboHeadIsActivated);
  };

  return (
    <>
      <Head>
        <title>Rambo Party Productions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {ramboHeadIsActivated ? (
        <div
          className={`bg-black w-screen h-screen fixed z-50 flex justify-center text-center`}
        >
          <div className="my-auto cursor-pointer">
            <h1 className="text-white text-3xl animate-pulse mb-5">
              click for maXimum party
            </h1>
            <img
              src="rambo-head.png"
              alt=""
              className="cursor-pointer mx-auto"
              onClick={ramboHeadClickHandler}
            />
          </div>
        </div>
      ) : (
        <div>
          <img
            src={gifSource}
            alt=""
            className={`absolute mx-auto left-0 right-0 top-0 bottom-0 my-auto w-full  z-20 ${
              isPartyExplosionActivated ? "block" : "hidden"
            }`}
          />

          <img
            src="rambo-keytar.png"
            alt=""
            className={`absolute mx-auto left-0 right-0 top-0 bottom-0 my-auto md:h-full w-auto  z-30 ${
              isPartyExplosionActivated ? "block" : "hidden"
            }`}
          />
        </div>
      )}

      <main className="min-h-screen relative">
        <Header ramboHeadActivate={ramboHeadClickHandlerNoAudio} />
        <Promo upcomingEvents={upcomingEvents} />
        {ramboHeadIsActivated ? <></> : <Footer />}
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "upcomingEvents"]{
    _id,
    _createdAt,
    title,
    author -> {
    name,
    image
  },
      url,
      eventDate,
  image,
  body,
  slug
  }`;

  const upcomingEvents = await client.fetch(query);

  return {
    props: {
      upcomingEvents,
    },
  };
};
